prefixes = [
    "The Great",
    "Mysterious",
    "Legendary",
    "Epic",
    "Shadowy",
    "Radiant",
    "Ancient",
    "Mythic",
    "Unseen",
    "Blazing",
    "Frozen",
    "Electric",
    "Shining",
    "Primal",
    "Luminous",
    "Golden",
    "Infinite",
    "Hidden",
    "Stormy",
    "Celestial",
    "The Ultimate",
    "Chaotic",
    "Wicked",
    "Forbidden",
    "Cosmic",
    "Spooky",
    "Turbo",
    "Ultra",
    "Phantom",
    "Fabled",
    "Crimson",
    "Dreamy",
    "Giga",
    "Almighty",
    "Surprise",
    "Whimsical",
    "The Unstoppable",
    "Dazzling",
    "Frenzied",
    "Glorious",
    "Bizarre",
    "Wacky",
    "Infinite",
    "Temporal",
    "Galactic",
    "Neon",
    "Holofoil",
    "Thunderous",
    "Fiery",
    "Frostbound",
    "Venomous",
    "Earthen",
    "Oceanic",
    "Tempestuous",
    "Twilight",
    "Mystic",
    "Solar",
    "Lunar",
    "Gale-Forged",
    "Blossom-Blessed",
    "Spectral",
    "Ironclad",
    "Shadow-Forged",
    "Arcane",
    "Plasma-Charged",
    "Molten",
    "Zephyr-Kissed",
    "Arceus’s",
    "Pikachu’s",
    "Eeveelution",
    "Mew’s",
    "Gengar’s",
    "Charizard’s",
    "Magikarp’s",
    "Lugia’s",
    "Ditto’s",
    "Jirachi’s",
    "Snorlax’s",
    "Rayquaza’s",
    "Pidgey-Powered",
    "Bulbasaur’s",
    "Psyduck’s",
    "Wobbuffet’s",
    "Zoroark’s",
    "Togepi’s",
    "Rotom’s",
    "Dialga’s"
]

suffixes = [
    "Bonanza",
    "Extravaganza",
    "Showdown",
    "Festival",
    "Gathering",
    "Raid",
    "Hunt",
    "Celebration",
    "Challenge",
    "Reckoning",
    "Tournament",
    "Quest",
    "Parade",
    "Carnival",
    "Conflux",
    "Ascension",
    "Outbreak",
    "Summit",
    "Clash",
    "Feast",
    "Meltdown",
    "Rumble",
    "Throwdown",
    "Scuffle",
    "Apocalypse",
    "Colosseum",
    "Eclipse",
    "Blitz",
    "Gauntlet",
    "Jamboree",
    "Brawl",
    "Saga",
    "Odyssey",
    "Frenzy",
    "Showstopper",
    "Inferno",
    "Mayhem",
    "Uprising",
    "Conquest",
    "Stampede",
    "Mystery Tour",
    "Time Warp",
    "Blast Off",
    "Vortex",
    "Fiesta",
    "Thunderstrike",
    "Emberfall",
    "Glacial Rush",
    "Toxic Bloom",
    "Seismic Clash",
    "Tidal Surge",
    "Solar Flare",
    "Moonfall",
    "Tempest Rumble",
    "Verdant Bloom",
    "Phantom Parade",
    "Ironstorm",
    "Arcane Duel",
    "Plasma Blitz",
    "Lavaflow",
    "Starfall",
    "Blossom Frenzy",
    "Echoing Roar",
    "Crystal Veil",
    "Zenith",
    "Trainer’s Trial",
    "Pokédex Quest",
    "Evolution Surge",
    "Gym Leader Gauntlet",
    "Shiny Hunt",
    "Legendary Call",
    "Battle Frontier",
    "Professor’s Challenge",
    "Rocket Takeover",
    "Safari Stampede",
    "Poké Ball Brawl",
    "Champion’s Gambit",
    "Elite Four Clash",
    "Mystery Gift Madness",
    "Daycare Derby",
    "Pokétopia Frenzy",
    "Eggstravaganza",
    "Ultra Wormhole",
    "Master Ball Madness",
    "Pokérus Outbreak"
]