halfed = ["Double-edge",
          "Selfdestruct",
          "Phoenix Burn",
          "Giga Impact",
          "Iron Bash",
          "Tropical Hour-GX",
          "Final Blowup",
          "Steam Blast",
          "Max Pyro Ball",
          "Crown Opal",
          "Rock Blaster",
          "Buster Tail",
          "Fulgurite",
          "Explosive Vortex",
          "G-Max Wildfire",
          "Max Thunder and Lightning",
          "Leaf Guard",
          "Explosion",
          "Blood Moon",
          "Crimson Dive",
          "Earthen Spike",
          "Flare Strike",
          "Full Metal Blade",
          "G-Max Boulder",
          "G-Max Chi Strike",
          "Giga Hammer",
          "Haymaker",
          "Heavy Rock Artillery",
          "Hydro Break",
          "Jurassic Hammer",
          "Laser Blade",
          "Max Fist",
          "Metal Defender",
          "Miracle Force",
          "Photon Blaster",
          "Reforged Axe",
          "Star Chronos",
          "Super Splash",
          "Swing and Skedaddle",
          "Topaz Bolt",
          "Wild Blaze",
          "Wind Pressure",
          "Wood Hammer"
          ]
