threeforths = ["Rampaging Fang",
               "Shadow Impact",
               "G-Max Riot",
               "Assault Tackle",
               "Sky-High Claws",
               "Lightning Ride-GX",
               "Ice Burn",
               "Psychic Loop",
               "Canyon Axe",
               "Hydro Kick",
               "Bright Horns",
               "Max Discharge",
               "Heavy Slam",
               "Wild Impact",
               "Earthquake",
               "Heavy Stomp",
               "Spiky Knuckle",
               "Blue Surge-GX",
               "G-Max Pulverization",
               "Max Heat Burst"
               ]
