threeforths = ["Rampaging Fang",
               "Shadow Impact",
               "G-Max Riot",
               "Assault Tackle",
               "Sky-High Claws",
               "Lightning Ride-GX",
               "Ice Burn",
               "Psychic Loop",
               "Canyon Axe",
               "Hydro Kick",
               "Bright Horns",
               "Max Discharge",
               "Heavy Slam",
               "Wild Impact",
               "Earthquake",
               "Heavy Stomp",
               "Spiky Knuckle",
               "Blue Surge-GX",
               "G-Max Pulverization",
               "Max Heat Burst",
               "Arrogant Impact",
               "Blizzard Burn",
               "Explosive Kick",
               "Flamethrower",
               "G-Max Pulverization(¾)",
               "Hydro Splash",
               "Hydro Lander",
               "Inferno Onrush",
               "Luster Purge",
               "Max Balloon",
               "Max Bullet",
               "Paralyzing Ball",
               "Pelagic Blade",
               "Scalding Block",
               "Scorching Fire",
               "Shinobi Blade",
               "Slashing Strike",
               "Sparking Strike",
               "Torrential Cannon",
               "Tyrannical Hole",
               "Wild Impact(¾)",
               "Wrack Down"
               ]
