whitelist = ["Dragon Pulse",
             "Max Drain",
             "Fire Spin",
             "Reversing Storm",
             "Ice Hammer",
             "Heavy Impact",
             "Leaf Cyclone",
             "Knuckle Sandwich",
             "Twin Cannons",
             "Land Crush",
             "Black Lance",
             "G-Max Smite",
             "Electro Cannon",
             "Air Slash",
             "Arm Press",
             "Armor Cannon",
             "Baryon Beam",
             "Best Dash",
             "Binding Greed",
             "Bite Off",
             "Brain Shake",
             "Brilliant Flare",
             "Burning Darkness",
             "Burning Train",
             "Lord's Valley"
             ]
